# Generated by Django 5.0.6 on 2024-06-23 09:14

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first_name', models.CharField(blank=True, max_length=254, null=True)),
                ('user_last_name', models.CharField(blank=True, max_length=254, null=True)),
                ('user_phone_number', models.CharField(blank=True, max_length=254, null=True)),
                ('user_street_address1', models.CharField(blank=True, max_length=254, null=True)),
                ('user_street_address2', models.CharField(blank=True, max_length=254, null=True)),
                ('user_city', models.CharField(blank=True, max_length=254, null=True)),
                ('user_country', models.CharField(blank=True, max_length=254, null=True)),
                ('user_postcode', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('user_delivery_notes', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
