# Generated by Django 5.0.6 on 2024-06-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0002_rename_userdetails_userdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='user_delivery_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
