# Generated by Django 5.0.6 on 2024-06-23 09:58

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0003_alter_userdetail_user_delivery_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='user_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='user_postcode',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
