# Generated by Django 5.0.6 on 2024-07-08 19:31

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0005_userdetail_wish_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='user_city',
            field=models.CharField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='user_country',
            field=django_countries.fields.CountryField(blank=True, default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='user_delivery_notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='user_first_name',
            field=models.CharField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='user_last_name',
            field=models.CharField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='user_phone_number',
            field=models.CharField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='user_postcode',
            field=models.CharField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='user_street_address1',
            field=models.CharField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='user_street_address2',
            field=models.CharField(blank=True, default='', max_length=254, null=True),
        ),
    ]
