# Generated by Django 5.0.6 on 2024-06-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('ref', models.CharField(max_length=254)),
                ('desc', models.TextField()),
                ('watch_brand', models.CharField(max_length=50)),
                ('watch_gender', models.CharField(max_length=6)),
                ('watch_case_size', models.IntegerField()),
                ('watch_material', models.CharField(max_length=20)),
                ('watch_dial_colour', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
