# Generated by Django 5.0.6 on 2024-06-19 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_image_product_image_main_product_image_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_main',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image_2',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image_3',
            new_name='image3',
        ),
    ]
