# Generated by Django 5.0.6 on 2024-06-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_image_main_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_discounted',
            field=models.IntegerField(default=0),
        ),
    ]
