# Generated by Django 5.0.6 on 2024-06-20 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_is_discounted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_discounted',
            new_name='discount_percentage',
        ),
    ]
