# Generated by Django 5.0.6 on 2024-06-24 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='watch_brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='watch_gender',
        ),
    ]
