# Generated by Django 5.0.6 on 2024-06-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_product_watch_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='watch_brand',
            field=models.CharField(choices=[('BR', 'Breitling'), ('TA', 'Tag Heuer'), ('OM', 'Omega'), ('TI', 'Tissot')], default='BR', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='watch_gender',
            field=models.CharField(choices=[('M', "Men's Watch"), ('F', "Women's Watch")], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
