# Generated by Django 5.0.6 on 2024-06-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_watch_brand_product_watch_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='watch_gender',
            field=models.CharField(choices=[('M', "Men's Watch"), ('F', "Women's Watch"), ('X', 'Unisex Watch')], max_length=1),
        ),
    ]
