# Generated by Django 5.0.6 on 2024-06-26 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0009_alter_product_watch_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSingleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_id', models.CharField(max_length=254)),
                ('product_name_text', models.CharField(max_length=254)),
                ('product_ref_text', models.CharField(max_length=254)),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
        ),
    ]
