# Generated by Django 5.0.6 on 2024-06-26 13:08

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_checkoutsingleitem_product_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutsingleitem',
            old_name='bag_id',
            new_name='order_number',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=254)),
                ('date_ordered', models.DateField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('phone_number', models.CharField(max_length=254)),
                ('street_address1', models.CharField(max_length=254)),
                ('street_address2', models.CharField(blank=True, max_length=254)),
                ('city', models.CharField(blank=True, max_length=254, null=True)),
                ('postcode', models.CharField(blank=True, max_length=254, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('delivery_notes', models.TextField(blank=True)),
                ('order_total', models.IntegerField()),
                ('watch_care_plan', models.BooleanField()),
                ('grand_total', models.IntegerField()),
                ('stripe_pid', models.CharField(max_length=254)),
                ('items_ordered', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkout.checkoutsingleitem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
