# Generated by Django 5.0.6 on 2024-06-26 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_rename_bag_id_checkoutsingleitem_order_number_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items_ordered',
        ),
    ]
