# Generated by Django 5.0.6 on 2024-06-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_remove_order_items_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='name@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
