# Generated by Django 5.0.6 on 2024-07-05 07:57

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(default='Linz', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(default='AU', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.CharField(default='0000', max_length=254),
            preserve_default=False,
        ),
    ]
