# Generated by Django 5.0.6 on 2024-06-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=254)),
                ('customer_email', models.EmailField(max_length=254)),
                ('product_name', models.CharField(max_length=254)),
                ('product_ref', models.CharField(max_length=254)),
                ('customer_message', models.TextField()),
            ],
        ),
    ]
