# Generated by Django 5.0.6 on 2024-06-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_newslettersignup_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.CharField(max_length=6)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
