# Generated by Django 5.0.6 on 2024-06-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_discountcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletter_signups', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='customermessage',
            name='product_name',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='customermessage',
            name='product_ref',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
