# Generated by Django 5.0.6 on 2024-06-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_sitestatistic_delete_sitestatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitestatistic',
            name='newsletter_signups',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
