# Generated by Django 5.0.6 on 2024-06-30 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_sitestatistic_newsletter_signups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteStatistic',
        ),
    ]
